name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP, Composer, and Xdebug
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, pdo_mysql, xdebug
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup environment
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Run Laravel Sail setup script
      run: |
        docker run --rm \
          -v $(pwd):/opt \
          -w /opt \
          laravelsail/php83-composer:latest \
          bash -c "composer install --ignore-platform-reqs"

    - name: Start Laravel Sail
      run: |
        ./vendor/bin/sail up -d

    - name: Create Coverage Directory
      run: mkdir -p coverage

    - name: Execute tests with coverage
      run: ./vendor/bin/sail test --coverage

    - name: Display coverage text report
      run: cat coverage/coverage.txt

    - name: Tear down Laravel Sail
      run: ./vendor/bin/sail down